### ISSUE TITLE
Bump to 12.0.0 and sugestions

### ISSUE THREAD

**Issue by mbevc1** [nextcloud/server-packages#10]
Seems like v12 is out. Are you planning to bump to that version? Probably just a version change.

There a few suggestions:
* It would be good to handle upgrades as well with `occ upgrade` and restart Apache;
* There are some duplicates upon building on C7, possible solve:
```
%files
%defattr(0640,root,%{nc_group},0750)
%dir %attr(0755,root,%{nc_group}) %{nc_dir}
%attr(0755,%{nc_user},%{nc_group}) %{nc_dir}/occ
%attr(0750,%{nc_user},%{nc_group}) %{nc_dir}/apps
%attr(0750,%{nc_user},%{nc_group}) %{nc_dir}/assets
%attr(0750,%{nc_user},%{nc_group}) %{nc_dir}/updater
%attr(0775,%{nc_user},%{nc_group}) %{nc_data_dir}
%attr(0775,%{nc_user},%{nc_group}) %{nc_config_dir}
%attr(0755,%{nc_user},%{nc_group}) %{nc_dir}/lib
%attr(0755,%{nc_user},%{nc_group}) %{nc_dir}/core
%attr(0755,%{nc_user},%{nc_group}) %{nc_dir}/settings
%attr(0755,%{nc_user},%{nc_group}) %{nc_dir}/3rdparty
%attr(0755,%{nc_user},%{nc_group}) %{nc_dir}/resources
%attr(0755,%{nc_user},%{nc_group}) %{nc_dir}/themes
%attr(0755,%{nc_user},%{nc_group}) %{nc_dir}/ocs*
%attr(0755,%{nc_user},%{nc_group}) %{nc_dir}/l10n
%attr(0755,%{nc_user},%{nc_group}) %{nc_dir}/*.php
%attr(0755,%{nc_user},%{nc_group}) %{nc_dir}/AUTHORS
%attr(0755,%{nc_user},%{nc_group}) %{nc_dir}/db_structure.xml
%attr(0755,%{nc_user},%{nc_group}) %{nc_dir}/index.html
%attr(0755,%{nc_user},%{nc_group}) %{nc_dir}/robots.txt


%config(noreplace) %attr(0644,%{nc_user},%{nc_group}) %{nc_dir}/.user.ini
%config(noreplace) %attr(0644,%{nc_user},%{nc_group}) %{nc_dir}/.htaccess
%config(noreplace) %attr(0644,root,root) /etc/httpd/conf.d/nextcloud.conf

%defattr(0644,%{nc_user},%{nc_group},0755)
```
* Maybe support for non FPM-PHP would nice;
* No sure placing outside of `/var/www/html` on RHEL/CentOS is a smart idea - SELinux wise.

**Comment by gsanchietti** [comment]
We will support any Nextcloud release until all minimum requirements are met.

> Maybe support for non FPM-PHP would nice;

To have this feature we need to split the package in 3 separate rpms:
- nextcloud files
- php-fpm configuration
- mod_php configuration for httpd24-httpd (rh-php56-php requires httpd24-httpd)

This is a little bit too much work for me now, but I will gladly review and accept PR.

> No sure placing outside of /var/www/html on RHEL/CentOS is a smart idea - SELinux wise.

This package doesn't take care at all of SELinux. I followed this doc for packaging guidelines:
https://fedoraproject.org/wiki/Packaging:Guidelines#Web_Applications

> There are some duplicates upon building on C7, possible solve:

Applied your fixes, excellent work!

> It would be good to handle upgrades as well with occ upgrade and restart Apache;

The goal of this rpm is to have a really simple installation and leave the configuration to the administrator.
If you're interested we handle all the provision and upgrade in our platform (https://github.com/NethServer/nethserver-nextcloud)

Here you can also find a testing package: http://packages.nethserver.org/nethserver/7/testing/x86_64/Packages/nextcloud-12.0.0-1.ns7.noarch.rpm

**Comment by mbevc1** [comment]
Thanks for your feedback! Looks interesting what you're doing with NethServer, but I think I'd need a more generic package for RHEL/CentOS and since EPEL project looks a bit stalled I'll probably just pushed new GH repo with generic distro builds. I can send you link for it, and maybe you'll find something useful for your project as well 🙂

**Comment by gsanchietti** [comment]
I'd like to join the effort, if possible.
I also don't mind to change our downstream package to adapt to a new format.
Probably we can also maintain a single spec to generate multiple RPMs.

Maybe you could link here your fork and we can see how merge everything together.
What do you think?

**Comment by mbevc1** [comment]
Sure, let met get that repo created and I can drop a link here 🙂

**Comment by mbevc1** [comment]
[Repo](https://github.com/mbevc1/nextcloud) is ready and provides basic building of packages. Haven't tried installation, thought ;)

**Comment by gsanchietti** [comment]
Thank you, I looked into your spec, great work!

But I have a couple of concerns:

- the spec assumes that php > 5.6 is installed, which is true for Fedora but not for RHEL or Centos, how do you deal with it?
- if an error occurs inside %pre or %post section, yum transaction is aborted; is it save to add there occ commands?

**Comment by mbevc1** [comment]
Thanks, well going to push some changes today, since I've discovered some minor bugs there trying to deploy it. 

Regarding your concerns:
- I'm aware of lack of PHP>=5.6 on CentOS/RHEL, but you can still use IUS or Remi repos: https://support.rackspace.com/how-to/install-epel-and-additional-repositories-on-centos-and-red-hat/
- If an error occurs in Yum transaction we should check why this failed and Nextcloud should be probably left in maintenance until problems are solved. Or did you have another situation in mind?

**Comment by gsanchietti** [comment]
>  but you can still use IUS or Remi repos

Next I will try to create a spec which can satisfy both user cases.

>  Or did you have another situation in mind?

I don't think there is any valid alternative.
This why I prefer to leave all configuration tasks outside yum transaction.

**Comment by mbevc1** [comment]
I don't think you can actually do conditional `Requires` until RPM >= 4.13 , CentOS7 uses 4.11. If you find another solution this would be great.

Actually I don't see this as a big issue, since `occ` commands should succeed, if they don't there are bigger issues needs resolving first.

Just pushed fixed `spec`, first one was missing few files from source ;)

**Comment by gsanchietti** [comment]
You're right, there is no simple solution.

I will move on with current implementation and update the README file to point also to your spec.
Thank you for your time!

**Comment by gsanchietti** [comment]
RPMs released, README updated (https://github.com/nextcloud/server-packages/blob/master/centos/README.md#alternatives-rpms).
