### ISSUE TITLE
Fedora

### ISSUE THREAD

**Issue by LorbusChris** [nextcloud/server-packages#19]
Hello :smiley: 
I've been doing some deving on updating Fedora's NextCloud rpm: https://github.com/LorbusChris/nextcloud-rpm
(I'm hoping to upstream the changes made there to the official Fedora repos.)

CentOS is family and I think we can probably make use of some synergies here =)

**Comment by gsanchietti** [comment]
Thank you for your contribution, what are the main differences from the Fedora RPM?

**Comment by LorbusChris** [comment]
I haven't compared the specs in detail, but for Fedora I did some unbundling of deps, loading them from the distro with a custom fedora-autoloader. I also checked all Licenses to be sure to include all bundled ones in the License field of the spec.

**Comment by gsanchietti** [comment]
I'm closing this issue since there are no news on it. Feel free to reopen with an associated PR.
