### ISSUE TITLE
Centos: pkgs availability as repo

### ISSUE THREAD

**Issue by MAngel666** [nextcloud/server-packages#24]
Hi

could you make a repo with the pkgs for centos?
I use spacewalk for my systems and it would be nice to get the pkgs automaticly...

TiA
Greetz
PS: Great work!

**Comment by DavidePrincipi** [comment]
Point YUM to

http://packages.nethserver.org/nethserver/7/updates/x86_64/

**Comment by MAngel666** [comment]
thx a lot!
