### ISSUE TITLE
Previous Major Support?

### ISSUE THREAD

**Issue by chilinux** [nextcloud/server-packages#32]
Can you please keep the SPEC file for the previous major version?

According to the maintenance and release schedule for NextCloud, while version 15 is currently the latest version, version 14 does not go end of life until September 2019.

While it makes sense that nexcloud.spec will always refer to the latest version, it would be nice if there was a nextcloud14.spec and nextcloud15.spec for people that want to continue to use a specific major version which has not reached end of life yet.

One reason for wanting to use a previous major version may be to work-around a bug in the latest version or issues using a plugin that is critical to the user which doesn't support the latest version yet.

**Comment by gsanchietti** [comment]
It's ok for me, we can create a v14 branch with the old spec version.
What do you think @alepolidori ?

Are you willing to maintain it @chilinux ?

**Comment by alepolidori** [comment]
@gsanchietti I agree. I've just created branch v14 to easily have `nextcloud.spec` to be used for stable version 14 as requested by @chilinux.

Is it ok @chilinux ?

**Comment by chilinux** [comment]
I already had forked the repository before the branch was created.  Since the branch didn't exist, right now my fork is flat with everything put into the master branch.

I'm willing to rebuild the fork but I would first like there to be a v15 and v16 branches to also populate as well as any guidance/feedback on what I have already done.

**Comment by gsanchietti** [comment]
I've created the v14 branch.

@chilinux would you like to create the PR to update to 14.0.8?

**Comment by chilinux** [comment]
I have created a purposed v14 PR based on 14.0.8

Please feel free to give me any feedback on what I could do better or different.

Thanks!

**Comment by gsanchietti** [comment]
Really good work!
Released: https://github.com/nextcloud/server-packages/releases/tag/centos-14.0.9

Remember to maintain it @chilinux ! ;)
