### ISSUE TITLE
Why was install path changed

### ISSUE THREAD

**Issue by sorvani** [nextcloud/server-packages#7]
Why was the install path moved out of /var/www/html? The official instructions still show to use the root of the webserver.

https://github.com/nextcloud/server-packages/commit/e80e48e929eb77d9f82e8092baf7ab8ba13aca4b

https://docs.nextcloud.com/server/11/admin_manual/installation/source_installation.html#apache-web-server-configuration

**Comment by KB7777** [comment]
Yes, it's unfortunate. CentOS default web server root is /var/www/html not /usr/share. It will be confusing.

**Comment by gsanchietti** [comment]
I changed the standard web root to follow upstream rules about packaging; no RPMs from EPEL/RHEL/Fedora install web application inside `/var/www/html`.
Please, see: https://fedoraproject.org/wiki/Packaging:Guidelines#Web_Applications

Also, you should change Nextcloud  configuration to save data in a subdirectory of ``/var/``.

**Comment by sorvani** [comment]
Reasons are awesome. Ok, I understand your reasoning. What about putting a symlink in /var/www/html and leaving the vhost file as it was?

**Comment by gsanchietti** [comment]
> What about putting a symlink in /var/www/html and leaving the vhost file as it was?

Again this is not standard-compliant but it should work.
But I don't understand the ratio behind it. What are you trying to achieve?

**Comment by sorvani** [comment]
So standards are nothing belongs in `/var/www/html/`? That seems crazy to me. What else is the Apache DocumentRoot for if not web stuff?

I ask because until your change nothing anywhere in Nextcloud documentation says to put anything anywhere except the DocumentRoot `/var/www/html`. This makes this CentOS package method different than every other Nextcloud install out there.

You have completely invalidated the documentation and help for anyone who subsequently installs Nextcloud form this repo.

**Comment by gsanchietti** [comment]
> You have completely invalidated the documentation and help for anyone who subsequently installs Nextcloud form this repo.

I know, this is why distribution package rules often doesn't work well with web application.

The maintainer of Nextcloud package from EPEL has a good blog post on it:

- https://www.hogarthuk.com/?q=node/17
- https://fedoramagazine.org/day-life-fedora-packager/
