### ISSUE TITLE
Proxy added to nextcloud.conf breaks a default install

### ISSUE THREAD

**Issue by sorvani** [nextcloud/server-packages#8]
The proxy line added here causes this error in a default install.
https://github.com/nextcloud/server-packages/commit/c4e817ac222d420db48c50bff5fc0a7eb66f6a48

```
[Thu Mar 16 15:32:49.355574 2017] [proxy:error] [pid 7016] (111)Connection refused: AH00957: FCGI: attempt to connect to 127.0.0.1:9000 (127.0.0.1) failed
[Thu Mar 16 15:32:49.355690 2017] [proxy:error] [pid 7016] AH00959: ap_proxy_connect_backend disabling worker for (127.0.0.1) for 60s
[Thu Mar 16 15:32:49.355712 2017] [proxy_fcgi:error] [pid 7016] [client 47.50.171.66:59168] AH01079: failed to make connection to backend: 127.0.0.1

```

**Comment by gsanchietti** [comment]
Nextcloud 11 can't work with standard CentOS PHP (5.4) release, the only viable solution is using PHP 5.6 from SCL repository.
You need to configure rh-php56-php-fpm to make it work.

If you install the package from upstream and start the service, you're almost done.

**Comment by sorvani** [comment]
So are you saying that with `rh-php56-php-fm` that proxy line works? Why is that proxy line needed though? Are you saying that Nextcloud 11 with PHP 5.6 from SCL does not work without the proxy line?

**Comment by gsanchietti** [comment]
> So are you saying that with rh-php56-php-fm that proxy line works?

Yes.

> Why is that proxy line needed though? 
Because it's how FPM works. See https://php-fpm.org/

To recap, these are the steps to have Nextcloud working on CentOS 7:

1.  Install and enable centos-release-scl repository:
```
yum install centos-release-scl
```
2. Install nextcloud:
```
yum install nextcloud
```
3. Enable the configuration
```
systemctl reload httpd
systemctl start rh-php56-php-fpm
```

Reference: https://www.softwarecollections.org/en/scls/rhscl/rh-php56/

**Comment by sorvani** [comment]
I get that this is how FPM works, but that di dnot answer my question as to why you have to use FPM in the first place. Is there some new feature of Nextcloud requiring it that I am obviously not aware of?

**Comment by DavidePrincipi** [comment]
I agree with @sorvani.  I'd go with mod_php56 module in apache. IIRC when scl is installed it is loaded by default (or a less invasive tweak is needed to enable it).

**Comment by sorvani** [comment]
The official documentation also says to use `mod_php` normally, and `php-fpm` for high load or limited RAM scenarios. So that should not be a default setting.
https://docs.nextcloud.com/server/11/admin_manual/installation/deployment_recommendations.html

**Comment by gsanchietti** [comment]
> I'd go with mod_php56 module in apache. 

mod_php56 is provided by `rh-php56-php` packages which requires `httpd24`.

> The official documentation also says to use mod_php normally, 

Yes, but it also says that the only PHP supported versions are PHP 5.6 or higer.

If we want to switch to Nextcloud 11, the simplest solution is to switch to PHP FPM.
Otherwise you can still use EPEL packages (released a couple of days ago), but only Nextcloud 10 will be supported.

**Comment by DavidePrincipi** [comment]
mod_php56 vs php-fpm. I see there are pro/cons on both solutions:

* mod_php: should work out of the box, but affects the global apache PHP environment (could be a problem)

* php-fpm: additional proxypass config and fpm daemon running, but keeps the standard PHP module on apache (could be safe)

**Comment by gsanchietti** [comment]
> mod_php: should work out of the box, but affects the global apache PHP environment (could be a problem)

It doesn't work out of the box. You will end with two httpd daemons listening on the same port.
You need a lot of configuration tuning to have it working,

**Comment by DavidePrincipi** [comment]
Thank you for the explanation, it's clear now!
